language: bash
matrix:
  include:
    - os: windows
      install: choco install mingw
      script: mingw32-make travis
    - os: windows
      env:
        - CMAKE_PATH="/c/Program Files/CMake/bin"
      script:
        - export PATH=$CMAKE_PATH:$PATH
        - mkdir build && cd build
        - cmake ..
        - cmake --build .
